/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatementsRouteImport } from './routes/statements'
import { Route as RevOps7k2pRouteImport } from './routes/rev-ops-7k2p'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as JoinRouteImport } from './routes/join'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AddMateRouteImport } from './routes/add-mate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevOps7k2pAnalyticsRouteImport } from './routes/rev-ops-7k2p.analytics'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'

const StatementsRoute = StatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const RevOps7k2pRoute = RevOps7k2pRouteImport.update({
  id: '/rev-ops-7k2p',
  path: '/rev-ops-7k2p',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMateRoute = AddMateRouteImport.update({
  id: '/add-mate',
  path: '/add-mate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevOps7k2pAnalyticsRoute = RevOps7k2pAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => RevOps7k2pRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-mate': typeof AddMateRoute
  '/bookings': typeof BookingsRoute
  '/join': typeof JoinRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/rev-ops-7k2p': typeof RevOps7k2pRouteWithChildren
  '/statements': typeof StatementsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/rev-ops-7k2p/analytics': typeof RevOps7k2pAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-mate': typeof AddMateRoute
  '/bookings': typeof BookingsRoute
  '/join': typeof JoinRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/rev-ops-7k2p': typeof RevOps7k2pRouteWithChildren
  '/statements': typeof StatementsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/rev-ops-7k2p/analytics': typeof RevOps7k2pAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-mate': typeof AddMateRoute
  '/bookings': typeof BookingsRoute
  '/join': typeof JoinRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/rev-ops-7k2p': typeof RevOps7k2pRouteWithChildren
  '/statements': typeof StatementsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/rev-ops-7k2p/analytics': typeof RevOps7k2pAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-mate'
    | '/bookings'
    | '/join'
    | '/payments'
    | '/profile'
    | '/rev-ops-7k2p'
    | '/statements'
    | '/checkout/success'
    | '/rev-ops-7k2p/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-mate'
    | '/bookings'
    | '/join'
    | '/payments'
    | '/profile'
    | '/rev-ops-7k2p'
    | '/statements'
    | '/checkout/success'
    | '/rev-ops-7k2p/analytics'
  id:
    | '__root__'
    | '/'
    | '/add-mate'
    | '/bookings'
    | '/join'
    | '/payments'
    | '/profile'
    | '/rev-ops-7k2p'
    | '/statements'
    | '/checkout/success'
    | '/rev-ops-7k2p/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddMateRoute: typeof AddMateRoute
  BookingsRoute: typeof BookingsRoute
  JoinRoute: typeof JoinRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  RevOps7k2pRoute: typeof RevOps7k2pRouteWithChildren
  StatementsRoute: typeof StatementsRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statements': {
      id: '/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rev-ops-7k2p': {
      id: '/rev-ops-7k2p'
      path: '/rev-ops-7k2p'
      fullPath: '/rev-ops-7k2p'
      preLoaderRoute: typeof RevOps7k2pRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-mate': {
      id: '/add-mate'
      path: '/add-mate'
      fullPath: '/add-mate'
      preLoaderRoute: typeof AddMateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rev-ops-7k2p/analytics': {
      id: '/rev-ops-7k2p/analytics'
      path: '/analytics'
      fullPath: '/rev-ops-7k2p/analytics'
      preLoaderRoute: typeof RevOps7k2pAnalyticsRouteImport
      parentRoute: typeof RevOps7k2pRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RevOps7k2pRouteChildren {
  RevOps7k2pAnalyticsRoute: typeof RevOps7k2pAnalyticsRoute
}

const RevOps7k2pRouteChildren: RevOps7k2pRouteChildren = {
  RevOps7k2pAnalyticsRoute: RevOps7k2pAnalyticsRoute,
}

const RevOps7k2pRouteWithChildren = RevOps7k2pRoute._addFileChildren(
  RevOps7k2pRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddMateRoute: AddMateRoute,
  BookingsRoute: BookingsRoute,
  JoinRoute: JoinRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  RevOps7k2pRoute: RevOps7k2pRouteWithChildren,
  StatementsRoute: StatementsRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
